---
- name: Crear directorio remoto si no existe
  file:
    path: "{{ remote_project_path }}"
    state: directory
    mode: '0755'

- name: Copiar laboratorio al servidor destino
  synchronize:
    src: "../infra-lab-docker/"
    dest: "{{ remote_project_path }}"
    recursive: yes
    delete: no

- name: Crear red labnet si no existe
  command: docker network create labnet
  register: net_create
  failed_when: net_create.rc != 0 and 'already exists' not in net_create.stderr
  changed_when: net_create.rc == 0

- name: Levantar servicios base APACHE/PYTHON/POSTGRES
  command: docker compose up -d --build
  args:
    chdir: "{{ remote_project_path }}"

- name: Levantar stack de monitoreo y observabilidad PROMETHEUS/GRAFANA/TEMPO/LOKI
  command: docker compose -f monitoring/docker-compose.monitor.yml up -d --build
  args:
    chdir: "{{ remote_project_path }}"

- name: Dar permisos de ejecución al script insertar_test.sh (Inserta datos de test)
  file:
    path: "{{ remote_project_path }}/monitoring/insertar_test.sh"
    mode: '0755'
    state: file

- name: Ejecutar el script insertar_test.sh (Inserta datos de test)
  command: ./insertar_test.sh
  args:
    chdir: "{{ remote_project_path }}/monitoring"
