{
 "title": "Dashboard - Observabilidad",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Resuest - Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{job=\"flask_app\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Resuest",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{job=\"flask_app\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRAZAS - TEMPO",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "filters": [
      { "id": "45d5fc14", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "python-flask-app" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"python-flask-app\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "LOGS - LOKI",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"python_app\"}"
    }
   ]
  }
 ]
}