global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']
  
  - job_name: 'flask_app'
    static_configs:
      - targets: ['python_app:5000']
    metrics_path: /metrics


