---
- name: Crear directorio remoto si no existe
  file:
    path: "{{ remote_project_path }}"
    state: directory
    mode: '0755'

- name: Copiar laboratorio al servidor destino
  synchronize:
    src: "../infra-lab-docker/"
    dest: "{{ remote_project_path }}"
    recursive: yes
    delete: no

- name: Crear red labnet si no existe
  command: docker network create labnet
  register: net_create
  failed_when: net_create.rc != 0 and 'already exists' not in net_create.stderr
  changed_when: net_create.rc == 0

- name: Levantar contenedores base con docker-compose (apps)
  command: docker compose up -d --build
  args:
    chdir: "{{ remote_project_path }}"

- name: Levantar stack de monitoreo
  command: docker compose -f monitoring/docker-compose.monitor.yml up -d --build
  args:
    chdir: "{{ remote_project_path }}"
